Added support for cuco.plug.co1
merdok/homebridge-miot pull request #83
Opened 2021-09-07 17:43 UTC by seanzhang98

2021-09-07 19:08 UTC, merdok commented
Thanks for the PR. Found one issue and could you also please add the device to the supported devices list?

2021-09-07 19:08 UTC, merdok requested changes

2021-09-07 19:08 UTC, merdok commented on lib/modules/outlet/devices/cuco.plug.co1.js
> +class CucoPlugCp1 extends OutletDevice {
You forgot to change the class name here. The export on the bottom is correct but it will not work because of this...

2021-09-09 03:12 UTC, seanzhang98 commented
fixed class and added device to support devices list

2021-09-09 16:49 UTC, merdok commented
Looks good! Thanks for the contribution!

2021-09-09 16:50 UTC, merged